name: Testing Github Action
on:
    push:
        branches: ['main']

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: print text
              run: echo "Hello World"