name: Testing Github Action
on:
    schedule:
        - cron: "*/1 * * * *"
    # push:
    #     branches: ['main']

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: print text
              run: echo "Hello World"