name: My First Workflow
on:
    schedule:
        - cron: "*/1 * * * *"
    push:
        branches: ['main']

jobs:
    first_job:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
            - name: print text
              run: echo "Hello World"
              #timeout-minutes: 1
            
            - name: run multiple commands
              run: |
                echo "This is another step"
                uptime
                ls