name: My First Workflow
on:    
    push:
        branches: ['main']

jobs:
    first_job:
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
          - uses: actions/checkout@v4
          - name: Put built assets in Artifacts
            uses: actions/upload-artifact@v4
            with:
              name: my-artifact
              path: |
                .
                !exlude.md
    
    second_job:
      runs-on: ubuntu-latest
      timeout-minutes: 1
      needs: [ first_job ]
      steps:
        - uses: actions/checkout@v4
        - name: Download Artifacts
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
            path: .

        - name: Check files
          run: ls