name: Explore Matrix Configuration
on:
    push:
        branches: ['main']

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-22.04, windows-latest]
                images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: see docker info
              run: docker info

            - name: running on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
    